version: "3.9"  # Specify a version
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile  # Corrected path
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=fixitdb;Username=postgres;Password=grupo07;Port=5434
    depends_on:
      - db
    healthcheck:  # Example health check
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Adapt to your application's health check endpoint.
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15 # Specify PostgreSQL version
    environment:
      - POSTGRES_DB=fixitdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=grupo07
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Example health check for Postgres
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
