name: Publish Image Docker

on:
  push:
    branches: [ main ] 
 # pull_request:
 #   branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_PASSWORD }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build 1 da Imagem Docker
      uses: docker/build-push-action@v3
      with:
        context: ./FIxIt.Server
        push: true
        tags: ${{ secrets.DOCKER_HUB_PASSWORD }}/projectfixit:latest 
